# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 945f71b87d3288717e3fa42218686f7e203126d7844ec8caff5d44007d065d267794167e8414e267a07f0c63448bfc4973e557b69877f3588532797244b7b228

test:
  secret_key_base: 84905d6b386d6226b8309b955875c4526dc067a1dc9f887910b1e0d15762505c35d291a6467785a304f65bb12ec7f1a61360b021807d115f8dfa989a3190d3ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
